{6080}{6178}{Y:i}I'll never join you.
{6179}{6333}{Y:i}If you only knew | the power of the dark side.
{6410}{6541}{Y:i}Obi One never told you what happened to your father!
{6584}{6690}{Y:i}He told me enough! | He told me you killed him.
{6713}{6803}{Y:i}No... I am your father!
{6843}{6911}(dramatic music playing)...
{6912}{7034}No, no that's not true... | That's impossible!
{7039}{7091}Search your feelings,| you know it's true.
{8259}{8389}{Y:b}Nooo…
